name: Format Pull Request Description

on:
  pull_request:
    types:
      - opened

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Remove comments from PR description
        uses: actions/checkout@v3
      - name: Update PR Description
        uses: nefrob/pr-description@master
        with:
          content: " "
          regex: "<!-- .* -->\n"
          regexFlags: img
          token: ${{ secrets.GITHUB_TOKEN }}
